### ISSUE TITLE
Compile errors after Update to v1.0.36:

### ISSUE THREAD

**Issue by StormTrooper** [kodi-game/game.libretro#34]
I'm doing the nightly OSMC builds with Leia. After this update I'm getting the following build errors.

```
In file included from /mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/client.cpp:22:0:
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/input/ControllerTopology.h:46:5: error: 'game_input_topology' does not name a type
     game_input_topology* GetTopology();
     ^~~~~~~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/input/ControllerTopology.h:48:30: error: 'game_input_topology' has not been declared
     static void FreeTopology(game_input_topology *topology);
                              ^~~~~~~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/input/ControllerTopology.h:56:20: error: 'GAME_PORT_TYPE' has not been declared
     bool SetDevice(GAME_PORT_TYPE portType, const std::string &controllerId);
                    ^~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/input/ControllerTopology.h:57:23: error: 'GAME_PORT_TYPE' has not been declared
     void RemoveDevice(GAME_PORT_TYPE portType);
                       ^~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/input/ControllerTopology.h:81:7: error: 'GAME_PORT_TYPE' does not name a type
       GAME_PORT_TYPE type;
       ^~~~~~~~~~~~~~
-- extracting...
     src='/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/download/rtmpdump-fa8646daeb19dfd12c181f7d19de708d623704c0.tar.gz'
     dst='/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/librtmp/src/librtmp'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 86%] Performing patch step for 'librtmp'
patching file Makefile
patching file Makefile
Hunk #1 succeeded at 2 with fuzz 2.
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/client.cpp:427:1: error: 'game_input_topology' does not name a type
 game_input_topology* GetTopology()
 ^~~~~~~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/client.cpp:432:19: error: variable or field 'FreeTopology' declared void
 void FreeTopology(game_input_topology* topology)
                   ^~~~~~~~~~~~~~~~~~~
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/client.cpp:432:19: error: 'game_input_topology' was not declared in this scope
/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro/src/client.cpp:432:40: error: 'topology' was not declared in this scope
 void FreeTopology(game_input_topology* topology)
                                        ^~~~~~~~
[ 86%] No update step for 'librtmp'
[ 86%] Performing configure step for 'librtmp'
CMakeFiles/game.libretro.dir/build.make:62: recipe for target 'CMakeFiles/game.libretro.dir/src/client.cpp.o' failed
make[5]: *** [CMakeFiles/game.libretro.dir/src/client.cpp.o] Error 1
make[5]: Leaving directory '/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro-prefix/src/game.libretro-build'
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/game.libretro.dir/all' failed
make[4]: *** [CMakeFiles/game.libretro.dir/all] Error 2
make[4]: Leaving directory '/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro-prefix/src/game.libretro-build'
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/mnt/package/mediacenter-next-osmc/src/xbmc-54b1d5a91092e81df7509c882568f68f5bece7a7/cmake/addons/build/game.libretro-prefix/src/game.libretro-build'
CMakeFiles/game.libretro.dir/build.make:112: recipe for target 'game.libretro-prefix/src/game.libretro-stamp/game.libretro-build' failed

```

Any pointers as to the issue?

**Comment by garbear** [comment]
Darn. I accidentally pushed the commit for https://github.com/kodi-game/game.libretro/pull/31 and it closed the pull request. Sorry about that, I'll merge https://github.com/xbmc/xbmc/pull/13499 ASAP.

**Comment by StormTrooper** [comment]
Thanks. I've created a patch for the pull request which is working. Run into another issue though. On LibretroTranslator.cpp you have LibretroTranslator::GetVideoFormat defined twice.

https://github.com/kodi-game/game.libretro/blob/master/src/libretro/LibretroTranslator.cpp#L37

https://github.com/kodi-game/game.libretro/blob/master/src/libretro/LibretroTranslator.cpp#L51

**Comment by garbear** [comment]
Haha double fail. Is that better?

**Comment by StormTrooper** [comment]
Thanks, that did the trick. Its building again.
